### ISSUE TITLE
keyring/env-var looks for exec: "dbus-launch": executable file in $PATH on centos host

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#104]
**Describe the bug**
```
Error: command 'kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL 
--image-repo $GITOPS_REPO_URL --dockercfgjson $DOCKERCONFIGJSON_PATH --git-host-access-token
 $GITHUB_TOKEN --output bootstrapresources --push-to-git=true', expected to succeed, exited with exit code: 1

Command stdout:   
Checking dependencies
 •  Checking if Sealed Secrets is installed with the default configuration  ...

 ✓  Checking if Sealed Secrets is installed with the default configuration [237ms]
 •  Checking if ArgoCD Operator is installed with the default configuration  ...

 ✓  Checking if ArgoCD Operator is installed with the default configuration [442ms]
 •  Checking if OpenShift Pipelines Operator is installed with the default configuration  ...

 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [510ms]
Adding .git to https://github.com/kam-bot/taxi-87
Adding .git to https://github.com/rhd-gitops-example/taxi


Command stderr:  ✗  unable to use access-token from keyring/env-var: exec: "dbus-launch": executable file not
 found in $PATH, please pass a valid token to --git-host-access-token
```

Details log - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/87/pull-ci-redhat-developer-kam-master-v4.5-integration-e2e/1333827600312700928#1:build-log.txt%3A943

**To Reproduce**

Locally its bit difficult to reproduce for now. You can apply ```/test all``` to my pr https://github.com/redhat-developer/kam/pull/87 and wait for job ```ci/prow/v4.5-integration-e2e``` to fail.

I will create a separate issue to track the work around how to replicate same environment like prow CI uses from our host machine 

NOTE: Prow uses this test container - https://github.com/redhat-developer/kam/blob/master/openshift-ci/build-root/Dockerfile

**Expected behavior**
keyring/env-var should not look for "dbus-launch": executable on centos host

**Screenshots**

**Additional context**

**Comment by amitkrout** [comment]
ping @bigkevmcd

**Comment by amitkrout** [comment]
I tried the same docker file that prow uses and build my custom container to reproduce the issue. Surprisingly i could not reproduce the issue, i mean kam bootstrap command does not report ```dbus``` error and the command works as expected.

Steps i executed

1. Sipnned up a 4.5 cluster
2. Copy ```kubeconfig```, ```kubeadmin-password``` and the auth file generated by the step https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/quay.md - ```<username>-robot-auth.json``` in the same dir where you want a Dockerfile to build the image.

3. $ cat Dockerfile
```
# Dockerfile to bootstrap build and test in openshift-ci

FROM registry.svc.ci.openshift.org/openshift/release:golang-1.14

RUN yum -y install dnf httpd-tools sudo

RUN wget https://openshift-release-artifacts.svc.ci.openshift.org/4.5.0-0.nightly-2020-12-02-105352/openshift-client-linux-4.5.0-0.nightly-2020-12-02-105352.tar.gz

RUN tar -xf openshift-client-linux-4.5.0-0.nightly-2020-12-02-105352.tar.gz

RUN cp oc /usr/local/bin/

COPY kubeadmin-password .

COPY kubeconfig .

COPY <username>-robot-auth.json .
```
4. From the same dir build the contaiiner image 

$ docker build --file Dockerfile -t docker.io/customcontainer .

5. Run the container 

$ docker run -it customcontainer

6. Then in the container run the command 
 ```
[root@930243aa5c33 origin]# cd ../.. && mkdir redhat-developer && cd redhat-developer/ && git clone https://github.com/redhat-developer/kam && cd kam/ && git fetch origin pull/87/head:pull_87 && git checkout pull_87 && mkdir auth && cp ../../openshift/origin/kubeadmin-password auth/ && cp ../../openshift/origin/kubeconfig auth/ && make prepare-test-cluster && make bin && cp bin/kam /usr/local/bin/
```
7. Do a kubeadmin login into the cluster

[root@930243aa5c33 kam]# oc login -u kubeadmin -p <password> <apiserver>

8. Run the command 
```
[root@930243aa5c33 kam]# kam bootstrap --service-repo-url https://github.com/amitkrout/taxi --gitops-repo-url https://github.com/amitkrout/gitops.git --image-repo quay.io/amitkrout/taxi --dockercfgjson ../../openshift/origin/<username>-robot-auth.json --git-host-access-token <token> --output resources
  
Checking dependencies

 ✓  Checking if Sealed Secrets is installed with the default configuration [1s]
 ✓  Checking if ArgoCD Operator is installed with the default configuration [2s]
 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [2s]
Adding .git to https://github.com/amitkrout/taxi
  
Completing Bootstrap process

 ✓  Authentication tokens encrypted in secrets
 ✓  Pipelines tracker has been configured
 ✓  OpenShift Pipelines resources created
 ✓  Openshift Route for EventListener created
 ✓  Created dev, stage and CICD environments
 ✓  Bootstrapped OpenShift resources successfully

 Next Steps:
 Please refer to https://github.com/redhat-developer/kam/tree/master/docs to get started.
```

**Comment by amitkrout** [comment]
I need to check with test-platform team on how they are building the container image

**Comment by amitkrout** [comment]
I am able to reproduce it locally with kam-bot github user, but surprisingly when i am using my github user token bootstrap does not complain any error. 

i am following exactly the same step as mentioned here at https://github.com/redhat-developer/kam/issues/104#issuecomment-737729323, instead of step 8 i am using the command 
```
# kam bootstrap --service-repo-url https://github.com/kam-bot/taxi --gitops-repo-url https://github.com/kam-bot/gitops.git --image-repo quay.io/kam-bot/taxi --dockercfgjson ../../openshift/origin/kam-bot-kambot-auth.json --git-host-access-token ***** --output resources
```

ping @bigkevmcd

**Comment by bigkevmcd** [comment]
The repository referred to in the service repository must exist.

**Comment by bigkevmcd** [comment]
I'm going to close this out, the issues were around env-vars misconfigured in the test.
