### ISSUE TITLE
Kam bootstrap command reports: failed to create repository "gitops" in namespace

### ISSUE THREAD

**Issue by gajanan-more** [redhat-developer/kam#111]
**Describe the bug**
```
✗  failed to create the gitops repository: "https://github.com/gajanan-more/gitops.git": failed to create repository "gitops" in namespace "": Repository creation failed.
```

**To Reproduce**
1. Run command 
```
kam bootstrap \
  --service-repo-url https://github.com/<your organization>/taxi.git \
  --gitops-repo-url https://github.com/<your organization>/gitops.git \
  --image-repo quay.io/<username>/<image-repo> \
  --dockercfgjson ~/Downloads/<username>-auth.json \
  --git-host-access-token <your git access token> \
  --output <path to write GitOps resources>
  --push-to-git=true
```
You will see error mentioned below,
```
✗  failed to create the gitops repository: "https://github.com/gajanan-more/gitops.git": failed to create repository "gitops" in namespace "": Repository creation failed.
```

**Expected behavior**
You should not receive any error.

**Comment by gajanan-more** [comment]
Removing `--push-to-git=true` worked

**Comment by amitkrout** [comment]
Yes, i am able to reproduce it.

**Comment by amitkrout** [comment]
@bigkevmcd Is the flag ```--push-to-git=true``` initializing a private repo ?

**Comment by gajanan-more** [comment]
![Screenshot from 2020-12-11 12-29-01](https://user-images.githubusercontent.com/17041173/101873207-8ebb8600-3bac-11eb-890f-59a822b96b26.png)

**Comment by amitkrout** [comment]
I have executed the same command through the automation script and it went fine, pass logs a are available at - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-developer_kam/87/pull-ci-redhat-developer-kam-master-v4.5-integration-e2e/1337011146581872640/artifacts/integration-e2e/integration-e2e-steps/container-logs/test.log

For cross verification i have re triggered the test. However i am execution same command locally, the same failure i can hit with manipulation of flag passing. For example

It works:
```
$ kam bootstrap --service-repo-url https://github.com/amitkrout/taxi --gitops-repo-url https://github.com/amitkrout/gitops.git --image-repo quay.io/amitkrout/taxi --dockercfgjson ~/Downloads/kam-bot-kambot-auth.json --git-host-access-token <token> --output resources --push-to-git=true
```

It fails:
```
$ kam bootstrap --service-repo-url https://github.com/amitkrout/taxi --gitops-repo-url https://github.com/amitkrout/gitops.git --image-repo quay.io/amitkrout/taxi --dockercfgjson ~/Downloads/kam-bot-kambot-auth.json --git-host-access-token <token> --output resources --push-to-git=true --overwrite
```

**Comment by bigkevmcd** [comment]
Yes, it creates a private repository.

**Comment by bigkevmcd** [comment]
@amitkrout Just to check, it fails if you use the same repository twice?

**Comment by amitkrout** [comment]
Yes, the repo was already present before the bootstrap command. @gajanan-more make sure that repo passed with the flag `--gitops-repo-url` should not present in your github namespace.

/close
