### ISSUE TITLE
Host key verification script implementation is flakey in CI

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#118]
**Is your feature request related to a problem? Please describe.**

Host key verification script passes here - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/87/pull-ci-redhat-developer-kam-master-v4.5-integration-e2e/1339168006101536768

However in the next run it fails with the error 
```
Command stderr:  ✗  failed to create the gitops repository: "https://github.com/kam-bot/taxi-87.git": failed to push bootstrapped resources: failed push remote to repository "git@github.com:kam-bot/taxi-87.git" "Could not create directory '/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n": exit status 128
```

In CI the script ideally add the attributes into the ```$HOME/.ssh/config``` file to skip the HostKeyChecking while creating github repo and pushing files.
```
$ cat  $HOME/.ssh/config
Host github.com
	StrictHostKeyChecking no
```

The script i am using for implementing it 
```bash
s.BeforeSuite(func() {
		fmt.Println("Before suite")
		if !envVariableCheck() {
			os.Exit(1)
		}
		val, ok := os.LookupEnv("CI")
		if ok && val == "prow" {
			err := os.MkdirAll(os.Getenv("HOME")+"/.ssh", 0755)
			if err != nil {
				fmt.Println(err.Error())
			}

			f, err := os.OpenFile(filepath.Join(os.Getenv("HOME"), ".ssh", "config"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
			if err != nil {
				log.Fatal(err)
			}
			if _, err = f.Write([]byte("Host github.com\n\tStrictHostKeyChecking no\n")); err != nil {
				f.Close() // ignore error; Write error takes precedence
				log.Fatal(err)
			}

			content, err := ioutil.ReadFile(filepath.Join(os.Getenv("HOME"), ".ssh", "config"))

			if err != nil {
				log.Fatal(err)
			}

			fmt.Println(string(content))

			if err := f.Close(); err != nil {
				log.Fatal(err)
			}
		}
	})
```

**Describe the solution you'd like**
The script implementation should not introduce any test flake

**Describe alternatives you've considered**

In the test feature file execute the command

```
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
```

**Additional context**

**Comment by bigkevmcd** [comment]
You could simplify the above code to something like...

```go
err := ioutil.WriteFile(filepath.Join(os.Getenv("HOME"), ".ssh", "config"), 0644)
```

**Comment by bigkevmcd** [comment]
Also...

```Go
err := os.MkdirAll(os.Getenv("HOME")+"/.ssh", 0700)
```

**Comment by amitkrout** [comment]
Updated through via - https://github.com/redhat-developer/kam/pull/87/commits/720dfec6f31463d7257a7a7664ffcbabe65fb262

The question is still open - why it the same script was flakey ? Either that should work properly or fail.

**Comment by amitkrout** [comment]
It will be addressed in https://github.com/redhat-developer/kam/issues/127
/close
