### ISSUE TITLE
Unable to create webhook

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/kam#152]
**Describe the bug**
```
kam  webhook create --env-name dev --service-name simple-nodejs-weather-app
```
fails with the following error

```
 ✗  unable to create webhook: failed to parse pipelines: 1 errors occurred:
invalid name "test-dev-app-simple-nodejs-weather-app-simple-nodejs-weather-app-binding": environments.test-dev.apps.app-simple-nodejs-weather-app.services.simple-nodejs-weather-app.pipelines.integration.binding
must be no more than 63 characters
```

When I look at the `pipelines.yaml` I can see that `environments[0].apps[0].services[0].pipelines.integration.bindings[0]` has value  `test-dev-app-simple-nodejs-weather-app-simple-nodejs-weather-app-binding` but this value is generated by bootstrap command and it should not generate an erroneous value.

**Comment by chetan-rns** [comment]
Closing this issue since it's already fixed
