### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by keithchong** [redhat-developer/kam#16]
**Describe the bug**
There is a spelling error in repository in the error message.  See webhook.go:

Unable to create webhook: failed to find Git repostory URL in manifest

**To Reproduce**
No need to reproduce, check line 86 of webhook.go

I saw this message when trying to create the webhook:

 ✗  Unable to create webhook: failed to find Git repostory URL in manifest

**Expected behavior**
Fix the spelling error.

**Additional context**
Going through GitOps Operation Day 1 https://github.com/redhat-developer/kam/blob/master/docs/journey/day1

**Comment by chetan-rns** [comment]
Thanks @keithchong !

**Comment by keithchong** [comment]
Hi @chetan-rns , no problem.
