### ISSUE TITLE
kam doesn't display version

### ISSUE THREAD

**Issue by chetan-rns** [redhat-developer/kam#188]
**Describe the bug**
`kam version` command doesn't display the CLI version of kam

**To Reproduce**
1. Build the binary from master
`go build ./cmd/kam`
2. Execute `./kam version`
3. Observe the version not displayed

**Expected behavior**
Executing `kam version` should print the release version of Kam

Example
`kam version v0.0.13-0-gbfb8090`

**Comment by wtam2018** [comment]
Do `make bin` which creates a binary in `bin`.   Or you can do `make install` which creates a binary in `$GOPATH/bin/kam`

**Comment by chetan-rns** [comment]
@wtam2018 Should we default the version to a hardcoded value if the flags are not passed? This would make the command work with plain `go build`

**Comment by wtam2018** [comment]
@chetan-rns I wouldn't bother to hard code anything in case `kam` is  compiled with plain `go build`.
