### ISSUE TITLE
master build version is lesser than the latest released version

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#19]
**Describe the bug**
See $SUBJECT

**To Reproduce**
```
$ make bin
go build -i -v -o gitops -ldflags="-s -w -X github.com/rhd-gitops-example/gitops-cli/pkg/cmd/version.Version=v0.0.2-10-g7dd5183" cmd/gitops-cli/gitops.go 

$ ./kam version
kam version v0.0.2-53-g946070d

Download latest release - https://github.com/redhat-developer/kam/releases/tag/v0.0.4
$ ./kam_darwin_amd64 version 
kam version v0.0.4-0-gcf34b16
```
**Expected behavior**
master build version should not less than latest release version. For example here the master version would be something like  v0.0.4-0-<last_commit_sha>

**Screenshots**
NA

**Additional context**
NA

**Comment by bigkevmcd** [comment]
By the looks of things, you're using an out of date checkout?

```shell
$ make bin
go build -i -v -o kam -ldflags="-s -w -X github.com/redhat-developer/kam/pkg/cmd/version.Version=v0.0.4-7-g946070d-dirty" 

$ ./kam version
kam version v0.0.4-7-g946070d-dirty
```

**Comment by amitkrout** [comment]
```
$ ./kam version
kam version v0.0.5-10-ga29421d
```
Looks good. 

My origin repo was somehow referring to the old gitops-cli deprecated repo. I cleaned up then version looks good now 👍 

/close
