### ISSUE TITLE
Kam on windows uses \ (backslash) in the paths

### ISSUE THREAD

**Issue by jduimovich** [redhat-developer/kam#209]
**Describe the bug**
When you run kam bootstrap or add service, it will place relative paths for the argocd directories.
These paths have "\" when generated on windows which fails when deployed to argocd

Argocd error is that the path is not found.
![image](https://user-images.githubusercontent.com/7844190/112565220-153e5100-8db3-11eb-993c-f9eeefa2f20e.png)

**To Reproduce**
1.  run kam bootstrap on window
2. My first service was named haproxy so it had  a "path: environments\dev\apps\app-haproxy\overlays"  as the directory in the Application definition.  This failed on Argocd when deployed  

When I manually replaced all \ with / universally in  the generated files, it was able to deploy 

![image](https://user-images.githubusercontent.com/7844190/112563789-6a2c9800-8db0-11eb-9410-82c09a91b779.png)

**Comment by keithchong** [comment]
Check also the kustomization.yaml file in /environments/dev/apps/app-haproxy/base. The backslashes should be forward slashes

**Comment by keithchong** [comment]
Hi @jduimovich , at your earliest convenience, could you please verify that the fix resolves the problem you are seeing?  Thanks in advance.  We'd like to close this issue/story out.

**Comment by jduimovich** [comment]
In the CI generated stuff (secrets and bindings), there were backslashes

g:\Dev\kamo\asp-gitops>git diff HEAD..HEAD~1
diff --git a/config/cicd/base/kustomization.yaml b/config/cicd/base/kustomization.yaml
index 74f9f5a..22fdda6 100644
--- a/config/cicd/base/kustomization.yaml
+++ b/config/cicd/base/kustomization.yaml
@@ -8,12 +8,12 @@ resources:
 - 03-secrets/docker-config.yaml
 - 03-secrets/git-host-basic-auth-token.yaml
 - 03-secrets/gitops-webhook-secret.yaml
**-- 03-secrets/webhook-secret-dev-a-simple-app.yaml
+- 03-secrets\webhook-secret-dev-a-simple-app.yaml**
 - 04-tasks/deploy-from-source-task.yaml
 - 05-pipelines/app-ci-pipeline.yaml
 - 05-pipelines/ci-dryrun-from-push-pipeline.yaml
 - 06-bindings/dev-app-a-simple-app-a-simple-app-binding.yaml
**-- 06-bindings/github-push-binding.yaml
+- 06-bindings\github-push-binding.yaml**
 - 07-templates/app-ci-build-from-push-template.yaml
 - 07-templates/ci-dryrun-from-push-template.yaml
 - 08-eventlisteners/cicd-event-listener.yaml
