### ISSUE TITLE
Minor documentation problems

### ISSUE THREAD

**Issue by tetchel** [redhat-developer/kam#21]
1. duplication in code block in https://github.com/redhat-developer/gitops-cli/blob/master/docs/FAQ/GitopsFAQ.md#i-have-a-non-globally-trusted-certificate-in-front-of-my-private-githubgitlab-installation-how-do-i-get-it-to-work

2. dead links in https://github.com/redhat-developer/gitops-cli/blob/master/docs/journey/day1/prerequisites/pipelines_operator.md
  First one should point to https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/img/pipelines-operator-install.gif
  Second one should point to https://github.com/redhat-developer/kam/blob/master/docs/updates/buildah.yaml

3. typo 'successfull' in day1

**Comment by bigkevmcd** [comment]
@tetchel can you explain #1 a bit more?

What do you think is duplicated?

**Comment by tetchel** [comment]
It appeared to me that the pipelineRef block was pasted one extra time, but I could be mistaken.

![image](https://user-images.githubusercontent.com/8888438/94166901-e245ef80-fe59-11ea-8908-6527d49e51e8.png)
