### ISSUE TITLE
[Doc]: CLI dcoument should introduce interactive mode. 

### ISSUE THREAD

**Issue by wtam2018** [redhat-developer/kam#30]
### Is your task related to a problem? Please describe.

Without mentioning in the document, Users won't know about running CLI in interactive mode.

### Describe the solution you'd like

Document how to run commands interactively.

### Describe alternatives you've considered

N/A
### Additional context

N/A

**Comment by chetan-rns** [comment]
@bigkevmcd @wtam2018 Should we just add a line saying it is supported? Or use https://asciinema.org/ and record a session with an interactive prompt. `odo` docs make use of asciinema https://github.com/openshift/odo#deploying-your-first-application

**Comment by bigkevmcd** [comment]
@chetan-rns asciicinema feels like a nice option.

We could also just add a note explaining how it works, with a completed run copied and pasted from the terminal (and perhaps edited for illustrative purposes).
