### ISSUE TITLE
Sealed Secrets Operator installation and configuration is incomplete

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#35]
**Describe the bug**
As per instructed in - https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/sealed_secrets.md it only says the installation of the operator, however to run ```kam bootstrap ...``` Sealed Secrets instance creation is needed as a preq check. 

**To Reproduce**
Follow steps as instructed - https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/sealed_secrets.md

**Expected behavior**
Sealed Secrets Instance creation steps should be added to the doc

**Screenshots**
NA

**Additional context**
NA

**Comment by bigkevmcd** [comment]
@amitkrout How can we improve the current documentation? It explains that you need to create a **SealedSecretsController** 

> Then create a "SealedSecretController" installation in the "cicd" namespace.

What would you like to see us add to that to make it simpler to understand?

**Comment by amitkrout** [comment]
> @amitkrout How can we improve the current documentation? It explains that you need to create a **SealedSecretsController**
> 
> > Then create a "SealedSecretController" installation in the "cicd" namespace
> 
> What would you like to see us add to that to make it simpler to understand?

@bigkevmcd It would be more specific if we add instance instead of installation. In the dash board i can see create an instance and it will pretty easy to understand as it matches the create instance link in the display. 

For example:

```Then create a "SealedSecretController" installation in the "cicd" namespace``` -> ```Then create a "SealedSecretController" instance in the "cicd" namespace```

**Comment by amitkrout** [comment]
@bigkevmcd You are too fast like 🚀 . I was about to send the pr haha...
