### ISSUE TITLE
Docs: References to https://github.com/<your organization>/....  should be changed

### ISSUE THREAD

**Issue by keithchong** [redhat-developer/kam#77]
**Describe the bug**
In the KAM Day 1 Operations, there are several references to GitHub repos where you have to fill in/replace the text.

For example: `https://github.com/<your organization>/taxi.git`

Instead of `<your organization>`, it should be the GitHub username

**To Reproduce**
Here is an example:
https://github.com/redhat-developer/kam/tree/master/docs/journey/day1#bootstrapping-the-manifest

**Comment by bigkevmcd** [comment]
@keithchong I'm not quite sure what you mean here?

What do you think the right username is here?

**Comment by bigkevmcd** [comment]
@keithchong Do you have any further thoughts on this?

**Comment by keithchong** [comment]
Hi Kevin, I missed the notification.   After our slack chat, I think we're good here.  As a user, I figured it out as to what to fill in there anyway.
