### ISSUE TITLE
Kam bootstrap reports failure in sealed secrets check

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/kam#94]
**Describe the bug**

Pasted output is self explanatory 
```
$ kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --image-repo $GITOPS_REPO_URL --dockercfgjson $DOCKERCONFIGJSON_PATH --git-host-access-token $GITHUB_TOKEN --output bootstrapresources --push-to-git=true'
Checking dependencies
 •  Checking if Sealed Secrets is installed with the default configuration  ...

 ✗  Checking if Sealed Secrets is installed with the default configuration [49ms] [Please install Sealed Secrets Operator from OperatorHub]
[...]
```
**To Reproduce**
1. Spinnup a cluster 4.5 or 4.6 or 4.7.
1. Install sealed secrets operator as per the doc https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/sealed_secrets.md
2. Install pipeline operator as per the doc https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/pipelines_operator.md
3. Install argocd operator as per the doc https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/argocd.md
4. Follow these instructions too

Create your [GitOps](https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/gitops_repo.md) repository and leave it uninitialized.
Application Source repository ([taxi](https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/service_repo.md) is used as an example in this document)
The external image repository secret to authenticate image pushes on successful pipeline execution. To use quay.io, please follow [prerequisites/quay.md](https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/quay.md)
Build kam binary - ```make bin``` and put the binary in the PATH
Steps to create the git access token for [GitHub](https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/github_access_token_steps.md) or [GitLab](https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/gitlab_access_token_steps.md).

5. Execute the command for bootstrapping the manifest 
```
$ kam bootstrap \
  --service-repo-url https://github.com/<your organization>/taxi.git \
  --gitops-repo-url https://github.com/<your organization>/gitops.git \
  --image-repo quay.io/<username>/<image-repo> \
  --dockercfgjson ~/Downloads/<username>-auth.json \
  --git-host-access-token <your git access token> \
  --output <path to write GitOps resources>
  --push-to-git=true
```
5. See error
```
Checking dependencies
 •  Checking if Sealed Secrets is installed with the default configuration  ...

 ✗  Checking if Sealed Secrets is installed with the default configuration [49ms] [Please install Sealed Secrets Operator from OperatorHub]
```

**Expected behavior**
Sealed Secrets check should pass

**Screenshots**

**Additional context**

**Comment by amitkrout** [comment]
@iam-veeramalla As per the pr #95 i am assuming you are not hitting the sealed secret check failure. Can you share your steps other than the doc we have for day 1 operation.

**Comment by bigkevmcd** [comment]
@iam-veeramalla just to check, you created a `SealedSecretController` per the instructions, and it's still not finding it?

Can you also paste the output of:

```shell
$ kubectl get sealedsecretcontrollers -n cicd
```

**Comment by bigkevmcd** [comment]
Now that we have our first kam bootstrap working, I'm going to close this out.

**Comment by amitkrout** [comment]
> Now that we have our first kam bootstrap working, I'm going to close this out.

/close
